site_name: {{cookiecutter.project_name}}
repo_url: https://github.com/partsnap/{{cookiecutter.project_name}}
site_url: https://partsnap.github.io/{{cookiecutter.project_name}}
site_description: {{cookiecutter.project_description}}
site_author: {{cookiecutter.author}}
edit_uri: edit/main/docs/
repo_name: partsnap/{{cookiecutter.project_name}}
copyright: Maintained by <a href="https://partsnap.com">{{cookiecutter.author}}</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mermaid2:
      version: 10.9.0
  - mkdocstrings:
      handlers:
        python:
          docstring_style: google
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  favicon: assets/partsnap-logo.png
  logo:
    icon: assets/partsnap-logo.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/partsnap/{{cookiecutter.project_name}}
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/{{cookiecutter.project_name}}

markdown_extensions:
  - toc:
      permalink: true
  - admonition:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
