name: Push Docker Registry

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "tag for docker image"
        required: true
        default: "latest"
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag depending on trigger
        id: set-tag
        shell: bash
        run: |
          if [ {% raw %}"${{ inputs.tag }}"{% endraw %} == "" ]; then
            echo "tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          else
            echo {% raw %}"tag=${{ inputs.tag }}"{% endraw %} >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}
          password: {% raw %}${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: mrusiniak/partstash:{% raw %}${{ steps.set-tag.outputs.tag }}{% endraw %}
