on:
    push:
        branches:
            - main
        tags-ignore:
            - '**'

name: merge-to-main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env

      - name: Run checks
        uses: ./.github/workflows/run-checks 
  {% if cookiecutter.tox== "y" %}
  tox:
    runs-on: ubuntu-latest
    needs: Quality
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env
        with: 
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Test with tox 
        run: |
          source .venv/bin/activate
          poetry add tox-gh-actions
          tox
  {% endif %}