on:
  release:
    types: [published]
    branches: [main]

name: release-main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env
        
      - name: Generate documentation
        run: |
            source .venv/bin/activate
            mkdocs gh-deploy