on:
  release:
    types: [published]
    branches: [main]

name: release-main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env

      - name: Run checks
        uses: ./.github/workflows/run-checks

  tox:
    runs-on: ubuntu-latest
    needs: Quality
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Test with tox 
        run: |
          source .venv/bin/activate
          poetry add tox-gh-actions
          tox

  release:
      needs: Tox
      runs-on: ubuntu-latest
      steps:

        - name: Check out
          uses: actions/checkout@v2

        - name: Set up the environment
          uses: ./.github/workflows/setup-poetry-env

        - name: Set output
          id: vars
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

        - name: Build and publish
          run: |
            source .venv/bin/activate
            poetry version $RELEASE_VERSION
            make build-and-publish
          env: 
            PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
            RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

  documentation:
    needs: Release
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env
        
      - name: Generate documentation
        run: |
            source .venv/bin/activate
            make docs-build

      - name: Deploy documentation to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build